// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUmagpiOSE6W03ZU9CRMorEIZwITLPDDc',
    appId: '1:599061225619:web:aca117f778e30ddeeaed66',
    messagingSenderId: '599061225619',
    projectId: 'agenda-flutter-c868c',
    authDomain: 'agenda-flutter-c868c.firebaseapp.com',
    storageBucket: 'agenda-flutter-c868c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM8ggREaZqkrzxMUPanoELZ9F4iP7ansQ',
    appId: '1:599061225619:android:a55654d88f4dda8aeaed66',
    messagingSenderId: '599061225619',
    projectId: 'agenda-flutter-c868c',
    storageBucket: 'agenda-flutter-c868c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKKjp1_eBFO9gTn4e0bW0tJ0Fe0Mi-hYE',
    appId: '1:599061225619:ios:47f9ddc4889d8d72eaed66',
    messagingSenderId: '599061225619',
    projectId: 'agenda-flutter-c868c',
    storageBucket: 'agenda-flutter-c868c.appspot.com',
    iosClientId: '599061225619-aa9lmtq3hgqjenrvii7dcikol7gnjuer.apps.googleusercontent.com',
    iosBundleId: 'com.agendadirebase.agendaFirabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKKjp1_eBFO9gTn4e0bW0tJ0Fe0Mi-hYE',
    appId: '1:599061225619:ios:47f9ddc4889d8d72eaed66',
    messagingSenderId: '599061225619',
    projectId: 'agenda-flutter-c868c',
    storageBucket: 'agenda-flutter-c868c.appspot.com',
    iosClientId: '599061225619-aa9lmtq3hgqjenrvii7dcikol7gnjuer.apps.googleusercontent.com',
    iosBundleId: 'com.agendadirebase.agendaFirabase',
  );
}
